version: '3.8'

services:

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./../data:/logs:ro                     # Monta tu carpeta con el log
    command: ["--strict.perms=false"]
    user: root
    depends_on:
      - logstash
    networks:
      - opensearch-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - node.name=opensearch-node1
      - cluster.name=opensearch-cluster-original
      - node.roles=cluster_manager,data
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_SECURITY_ADMIN_PASSWORD=Contrasena123456789$   # variable interna (opcional)
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Contrasena123456789$ # contraseña inicial obligatoria
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-node1-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - opensearch-net

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - node.name=opensearch-node2
      - cluster.name=opensearch-cluster-original
      - node.roles=cluster_manager,data
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_SECURITY_ADMIN_PASSWORD=Contrasena123456789$
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Contrasena123456789$     
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-node2-data:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-node3:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node3
    environment:
      - node.name=opensearch-node3
      - cluster.name=opensearch-cluster-original
      - node.roles=cluster_manager,data
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_SECURITY_ADMIN_PASSWORD=Contrasena123456789$
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Contrasena123456789$  
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-node3-data:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch-node2:9200","http://opensearch-node3:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Contrasena123456789$
      - SERVER_SSL_ENABLED=false          # para simplificar en local
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    depends_on:
      - opensearch-node2
      - opensearch-node3
    networks:
      - opensearch-net

volumes:
  opensearch-node1-data:
  opensearch-node2-data:
  opensearch-node3-data:

networks:
  opensearch-net:
    external: true
